### ISSUE TITLE
Resim görüntülenme sorunu

### ISSUE THREAD

**Issue by oguzhantasci** [akademihelp/site#10]
http://akademi.help/php-curl-ile-bulutfon-apisini-kullanarak-dahili-listesini-gostermek/ yazısındaki [resim](http://i.imgur.com/lxT4NSo.png) imgur engellendiği için görüntülenememekte. Bilginize.

**Comment by onurozgurozkan** [comment]
@coskuntekin belki resimleri locale alacak bir örnek yapılabilir. Bu konuyla ilgili nasıl bir yol izleyelim.

**Comment by coskuntekin** [comment]
@onurozgurozkan github uzerinde host edebiliriz.

**Comment by onurozgurozkan** [comment]
@coskuntekin bununla ilgili  "Resimler nerede host edilecek gibisinden" örnek bir kodu README.md ye yazabilir miyiz? Bundan sonraki yazarlar yazmadan önce o standarda uyarlar.

**Comment by coskuntekin** [comment]
@onurozgurozkan guncellemeyi yaptiktan sonra eklemistim abi. https://github.com/akademihelp/site/commit/1824fbf7f8f5b6ecff9d996e8c95cb12259977ed#diff-04c6e90faac2675aa89e2176d2eec7d8R12

**Comment by coskuntekin** [comment]
Gorsel eklemek icin `root/images` dizini kullanilabilir. 
Ornek kod `![Gorselin aciklamasi](/images/bulutfon-gelen-fakslarin-goruntulenmesi.png)`
