### ISSUE TITLE
Site build olmuyor. Jekyll 3.0'a taşınması gerekiyor. 

### ISSUE THREAD

**Issue by onurozgurozkan** [akademihelp/site#22]
Github Pages, Jeklly 3.0 destekliyor. @coskuntekin fyi.

**Comment by coskuntekin** [comment]
[github pages] (https://pages.github.com/versions/) v3.0.3 seklinde verilmis ama v3.1.1 de bir sorun goremedim. `grunt serve` yi kullanabilirsiniz.

**Comment by onurozgurozkan** [comment]
@coskuntekin şüan build oluyorsa sorun yok.
