### ISSUE TITLE
Reponun ismi akademi.help şeklinde değiştirilmeli.

### ISSUE THREAD

**Issue by tayfunoziserikan** [akademihelp/site#7]
Bir şekilde forklandığı zaman site ismi cok genel oldugu icin baska kisilerin depolarinda ilk etapta ne oldugu anlasilmiyor. Onerim repo isminin daha anlamlı hale getirilmesidir.

**Comment by onurozgurozkan** [comment]
@tayfunoziserikan ne diyelim? akademi/akademi.help mi yapalım? 

Birde README.md'ye ne olduğunu eklesek daha iyi olmaz mi?

**Comment by onurozgurozkan** [comment]
@coskuntekin sen bu konuda ne diyorsun?

**Comment by coskuntekin** [comment]
@onurozgurozkan akedemi-blog olabilir mesela...

**Comment by onurozgurozkan** [comment]
@coskuntekin bence şımdilik böyle kalsın sonra bakarız.
